/**
 * Root Layout Component
 * 
 * The main layout wrapper for the entire LangQuest application.
 * Provides global providers, fonts, and modal components that are available throughout the app.
 */

import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";  
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { ExitModal } from "@/components/modals/exit-modal";
import { HeartsModal } from "@/components/modals/hearts-modal";
import { PracticeModal } from "@/components/modals/practice-modal";

// Configure Nunito font for the entire application
const font = Nunito(
  {
  subsets: ["latin"],
});

// Application metadata for SEO and browser display
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Root layout component that wraps the entire application
 * 
 * Features:
 * - Clerk authentication provider for user management
 * - Global font configuration (Nunito)
 * - Toast notifications system
 * - Global modal components (Hearts, Practice, Exit)
 * 
 * @param children - Page components and nested layouts
 * @returns HTML document structure with global providers
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={font.className}
        >
          {children}
          {/* Global notification system */}
          <Toaster />
          
          {/* Global modal components available throughout the app */}
          <HeartsModal />
          <PracticeModal />
          <ExitModal />
        </body>
      </html>
    </ClerkProvider>
  );
}
